pg-codigo/codigo-yii/controllers/UsuarioController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Usuario;
use app\models\UsuarioSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsuarioController implements the CRUD actions for Usuario model.
 */
class UsuarioController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Updates an existing Usuario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionTrocarSenha()
    {
        $model = Usuario::findOne(Yii::$app->user->identity->getId());
        $senha = Yii::$app->request->post('Usuario')['senha'];

        if (!empty($senha)) {
            $model->senha = sha1($senha);
            if($model->save()){
                Yii::$app->getSession()->setFlash('mensagens', [
                    'type' => 'success',
                    'message' => 'Senha alterada com sucesso',
                ]);
            } else {
                Yii::$app->getSession()->setFlash('mensagens', [
                    'type' => 'danger',
                    'message' => 'Não foi possível alterar a senha',
                ]);
            }
            return $this->goBack();
        } else {
            return $this->render('trocar-senha', [
                'model' => $model,
            ]);
        }
    }
}

pg-codigo/codigo-yii/views/layouts/dashboard/_header.php
<?php

use yii\helpers\Html;

$usuario_logado = Yii::$app->user->identity;

$currentController = Yii::$app->controller->id;
$currentAction = Yii::$app->controller->action->id;

/**
 * OPÇÕES (INCLUSIVE DENTRO DE SUB-MENÚS)
 */
$afastamentos = $currentController === 'afastamento' ? 'active' : '';
$professores = $currentController === 'professor' ? 'active' : '';
$secretarios = $currentController === 'secretario' ? 'active' : '';
?>

<header class="header">
    <div class="header__logo">
        <h1><?= Html::a( Html::img('@web/images/logo/logo.svg', ['style' => 'width: 100px;']), ['/afastamento'])?></h1>
    </div>

    <ul class="top-nav">
        <li class="dropdown">
            <a href="" data-toggle="dropdown" aria-expanded="false" style="display: flex; align-items: center;"><i class="font-sendpayfont" style="font-size: 18px;">a</i><span style="margin-left: 10px;"><?= $usuario_logado->login ?></span></a>
            <div class="dropdown-menu dropdown-menu-right">
                <?= Html::a('Trocar senha', ['/usuario/trocar-senha'], ['class' => 'dropdown-item']) ?>
				<?= Html::a('Sair', ['/site/logout'], ['data-method' => 'post', 'class' => 'dropdown-item']) ?>
            </div>
        </li>
    </ul>

    <ul class="nav top-menu">
        <li class="nav-item <?= $afastamentos ?>"><?= Html::a('Afastamentos', ['/afastamento'], ['class' => 'nav-link'])?></li>
        <li class="nav-item <?= $professores ?>"><?= Html::a('Professores', ['/professor'], ['class' => 'nav-link'])?></li>
        <li class="nav-item <?= $secretarios ?>"><?= Html::a('Secretários', ['/secretario'], ['class' => 'nav-link'])?></li>
    </ul>
</header>

pg-codigo/codigo-yii/views/layouts/dashboard/main.php
<?php
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\helpers\Url;
use yii\web\View;

/* @var $this View */
/* @var $content string */

AppAsset::register($this);

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="<?= Url::base() ?>/js/jquery-1.7.2.js"></script>
</head>
<body>

    <?php $this->beginBody() ?>

        <body data-ma-theme="light-blue">
            <main class="main main--alt">

				<?= $this->render('../_flashes') ?>

                <?= $this->render('../_page-loader') ?>

                <?= $this->render('_header') ?>

                <section class="content content--full">
                    <div class="content__inner">
                        <?= $content ?>
                    </div>
                </section>
            </main>

    <?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>