pg-codigo/codigo-symfony/src/Entity/Afastamento.php
<?php

namespace App\Entity;

use App\Repository\AfastamentoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AfastamentoRepository::class)
 */
class Afastamento
{
    const TIPO_NACIONAL = 'nacional';
    const TIPO_INTERNACIONAL = 'internacional';

    const ONUS_TOTAL = 'total';
    const ONUS_PARCIAL = 'parcial';
    const ONUS_INEXISTENTE = 'inexistente';

    const SITUACAO_INICIADO = 'iniciado';
	const SITUACAO_AGUARDANDO_PARECER_RELATOR = 'aguardando_parecer_relator';
	const SITUACAO_LIBERADO = 'liberado';
    const SITUACAO_AGUARDANDO_DECISAO_DI = 'aguardando_decisao_di';
	const SITUACAO_APROVADO_DI = 'aprovado_di';
	const SITUACAO_APROVADO_CT = 'aprovado_ct';
	const SITUACAO_APROVADO_PRPPG = 'aprovado_prppg';
	const SITUACAO_ARQUIVADO = 'arquivado';
	const SITUACAO_CANCELADO = 'cancelado';
	const SITUACAO_REPROVADO = 'reprovado';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $data_solicitacao;

    /**
     * @ORM\Column(type="date")
     */
    private $data_inicio_afastamento;

    /**
     * @ORM\Column(type="date")
     */
    private $data_fim_afastamento;

    /**
     * @ORM\Column(type="date")
     */
    private $data_inicio_evento;

    /**
     * @ORM\Column(type="date")
     */
    private $data_fim_evento;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nome_evento;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $situacao;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tipo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $onus;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $motivo;

    /**
     * @ORM\Column(type="integer")
     */
    private $professor_solicitante_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $professor_relator_id;

    /**
     * @ORM\ManyToOne(targetEntity=Professor::class, inversedBy="meusAfastamentos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $professorSolicitante;

    /**
     * @ORM\ManyToOne(targetEntity=Professor::class, inversedBy="afastamentosSouRelator")
     */
    private $professorRelator;

    /**
     * @ORM\OneToMany(targetEntity=Parecer::class, mappedBy="afastamento")
     */
    private $pareceres;

    /**
     * @ORM\OneToMany(targetEntity=Documento::class, mappedBy="afastamento")
     */
    private $documentos;

    public function __construct()
    {
        $this->pareceres = new ArrayCollection();
        $this->documentos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDataSolicitacao(): ?\DateTimeInterface
    {
        return $this->data_solicitacao;
    }

    public function setDataSolicitacao(\DateTimeInterface $data_solicitacao): self
    {
        $this->data_solicitacao = $data_solicitacao;

        return $this;
    }

    public function getDataInicioAfastamento(): ?\DateTimeInterface
    {
        return $this->data_inicio_afastamento;
    }

    public function setDataInicioAfastamento(\DateTimeInterface $data_inicio_afastamento): self
    {
        $this->data_inicio_afastamento = $data_inicio_afastamento;

        return $this;
    }

    public function getDataFimAfastamento(): ?\DateTimeInterface
    {
        return $this->data_fim_afastamento;
    }

    public function setDataFimAfastamento(\DateTimeInterface $data_fim_afastamento): self
    {
        $this->data_fim_afastamento = $data_fim_afastamento;

        return $this;
    }

    public function getDataInicioEvento(): ?\DateTimeInterface
    {
        return $this->data_inicio_evento;
    }

    public function setDataInicioEvento(\DateTimeInterface $data_inicio_evento): self
    {
        $this->data_inicio_evento = $data_inicio_evento;

        return $this;
    }

    public function getDataFimEvento(): ?\DateTimeInterface
    {
        return $this->data_fim_evento;
    }

    public function setDataFimEvento(\DateTimeInterface $data_fim_evento): self
    {
        $this->data_fim_evento = $data_fim_evento;

        return $this;
    }

    public function getNomeEvento(): ?string
    {
        return $this->nome_evento;
    }

    public function setNomeEvento(string $nome_evento): self
    {
        $this->nome_evento = $nome_evento;

        return $this;
    }

    public function getSituacao(): ?string
    {
        return $this->situacao;
    }

    public function setSituacao(string $situacao): self
    {
        $this->situacao = $situacao;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->tipo;
    }

    public function setTipo(string $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getOnus(): ?string
    {
        return $this->onus;
    }

    public function setOnus(string $onus): self
    {
        $this->onus = $onus;

        return $this;
    }

    public function getMotivo(): ?string
    {
        return $this->motivo;
    }

    public function setMotivo(?string $motivo): self
    {
        $this->motivo = $motivo;

        return $this;
    }

    public function getProfessorSolicitanteId(): ?int
    {
        return $this->professor_solicitante_id;
    }

    public function setProfessorSolicitanteId(int $professor_solicitante_id): self
    {
        $this->professor_solicitante_id = $professor_solicitante_id;

        return $this;
    }

    public function getProfessorRelatorId(): ?int
    {
        return $this->professor_relator_id;
    }

    public function setProfessorRelatorId(?int $professor_relator_id): self
    {
        $this->professor_relator_id = $professor_relator_id;

        return $this;
    }

    public function getProfessorSolicitante(): ?Professor
    {
        return $this->professorSolicitante;
    }

    public function setProfessorSolicitante(?Professor $professorSolicitante): self
    {
        $this->professorSolicitante = $professorSolicitante;

        return $this;
    }

    public function getProfessorRelator(): ?Professor
    {
        return $this->professorRelator;
    }

    public function setProfessorRelator(?Professor $professorRelator): self
    {
        $this->professorRelator = $professorRelator;

        return $this;
    }

    /**
     * @return Collection|Parecer[]
     */
    public function getPareceres(): Collection
    {
        return $this->pareceres;
    }

    public function addParecere(Parecer $parecere): self
    {
        if (!$this->pareceres->contains($parecere)) {
            $this->pareceres[] = $parecere;
            $parecere->setAfastamento($this);
        }

        return $this;
    }

    public function removeParecere(Parecer $parecere): self
    {
        if ($this->pareceres->contains($parecere)) {
            $this->pareceres->removeElement($parecere);
            // set the owning side to null (unless already changed)
            if ($parecere->getAfastamento() === $this) {
                $parecere->setAfastamento(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Documento[]
     */
    public function getDocumentos(): Collection
    {
        return $this->documentos;
    }

    public function addDocumento(Documento $documento): self
    {
        if (!$this->documentos->contains($documento)) {
            $this->documentos[] = $documento;
            $documento->setAfastamento($this);
        }

        return $this;
    }

    public function removeDocumento(Documento $documento): self
    {
        if ($this->documentos->contains($documento)) {
            $this->documentos->removeElement($documento);
            // set the owning side to null (unless already changed)
            if ($documento->getAfastamento() === $this) {
                $documento->setAfastamento(null);
            }
        }

        return $this;
    }
}

pg-codigo/codigo-symfony/src/Form/AfastamentoType.php
<?php

namespace App\Form;

use App\Entity\Afastamento;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AfastamentoType extends AbstractType
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('data_inicio_afastamento', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('data_fim_afastamento', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('tipo', ChoiceType::class, [
                'choices' => [
                    'Nacional' => 'nacional',
                    'Internacional' => 'internacional'
                ]
            ])
            ->add('onus', ChoiceType::class, [
                'choices' => [
                    'Total' => 'total',
                    'Parcial' => 'parcial',
                    'Inexistente' => 'inexistente'
                ]
            ])
            ->add('motivo')
            ->add('nome_evento')
            ->add('data_inicio_evento', DateType::class, [
                'widget' => 'single_text',
            ])
            ->add('data_fim_evento', DateType::class, [
                'widget' => 'single_text',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Afastamento::class,
        ]);
    }
}

pg-codigo/codigo-symfony/templates/afastamento/_form.html.twig
<form name="afastamento" action="{{ path('afastamento_new') }}" method="post" enctype="multipart/form-data">
{{ form_row(form._token) }}

<div class="afastamento-form"  style="padding-bottom: 20px;">

    {% if form.vars.errors|length %}
    <div class="alert alert-danger alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        {{ form_errors(form) }}
    </div>
    {% endif %}

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Informações Básicas</h2>
            <small class="card-subtitle">Qual é o período do afastamento e qual o motivo?</small>
        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.data_inicio_afastamento, {'attr': {'class': 'form-control form-control--active'}}) }}
                        {{ form_label(form.data_inicio_afastamento) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.data_inicio_afastamento) }}</div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.data_fim_afastamento, {'attr': {'class': 'form-control form-control--active'}}) }}
                        {{ form_label(form.data_fim_afastamento) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.data_fim_afastamento) }}</div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.tipo, {'attr': {'class': 'form-control'}}) }}
                        {{ form_label(form.tipo) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.tipo) }}</div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.onus, {'attr': {'class': 'form-control'}}) }}
                        {{ form_label(form.onus) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.onus) }}</div>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.motivo, {'attr': {'class': 'form-control'}}) }}
                        {{ form_label(form.motivo) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.motivo) }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Sobre o Evento</h2>
            <small class="card-subtitle">Que evento é este e quando vai ocorrer?</small>
        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.nome_evento, {'attr': {'class': 'form-control'}}) }}
                        {{ form_label(form.nome_evento) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.nome_evento) }}</div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.data_inicio_evento, {'attr': {'class': 'form-control form-control--active'}}) }}
                        {{ form_label(form.data_inicio_evento) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.data_inicio_evento) }}</div>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group form-group--float">
                        {{ form_widget(form.data_fim_evento, {'attr': {'class': 'form-control form-control--active'}}) }}
                        {{ form_label(form.data_fim_evento) }}
                        <i class="form-group__bar"></i>
                        <div class="help-block">{{ form_errors(form.data_fim_evento) }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card" id="app">
        <div class="card-header">
            <h2 class="card-title">Documentos</h2>
            <small class="card-subtitle">Quais documentos justificam a solicitação de afastamento?</small>
        </div>
        <div class="card-block__nova-linha animated fadeInUp" v-for="(documento, i) in documentos" :key="i">
            <div class="row">
                <div class="col-lg-3">
                    <div class="form-group">
                        <label>Título</label>
                        <input v-model="documento.titulo" :name="'Documento['+i+'][titulo]'" type="text" class="form-control" placeholder="ex: Passagens aéreas, Banner do evento..." autocomplete="off" maxlength="100">
                        <i class="form-group__bar"></i>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="form-group">
                        <label>Arquivo</label>
                        <input type="file" :name="'Documento['+i+'][nome_arquivo]'" class="form-control" autocomplete="off">
                        <i class="form-group__bar"></i>
                    </div>
                </div>
                <div class="col-lg-6 text-right">
                    <div class="form-group" style="margin-top: 2rem;">
                        <button type="button" class="btn btn-outline-danger waves-effect" @click="removerDocumento(i)">Remover documento</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-block">
            <div class="row">
                <div class="col-lg-3">
                    <button type="button" class="btn btn-outline-primary waves-effect" @click="adicionarDocumento">Adicionar documento</button>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <button class="btn btn-primary">{{ button_label|default('Salvar') }}</button>
    </div>

</div>

</form>

<!--VUEJS-->
<!-- development version, includes helpful console warnings -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<!-- production version, optimized for size and speed -->
<!--<script src="https://cdn.jsdelivr.net/npm/vue"></script>-->
<!-- V-MASK -->
<script src="https://cdn.jsdelivr.net/npm/v-mask/dist/v-mask.min.js"></script>
<script>
    Vue.directive('mask', VueMask.VueMaskDirective);
    var app = new Vue({
        el: '#app',
        data: {
            documentos: {{ afastamento.documentos|serialize|raw }}
    },
    methods: {
        adicionarDocumento: function () {
            let novo = {
                titulo: '',
                nome_arquivo: ''
            }
            this.documentos.push(novo)
        },
        removerDocumento: function (i) {
            this.documentos.splice(i, 1)
        }
    }
    })
</script>

pg-codigo/codigo-symfony/templates/afastamento/edit.html.twig
{% extends 'layouts/main.html.twig' %}

{% block title %}Editar Cadastro do Professor{% endblock %}

{% block body %}

    <header class="content__title">
        <h1>Editar Cadastro do Professor</h1>
    </header>

    {{ include('professor/_form.html.twig', {'button_label': 'Salvar Modificações'}) }}

{% endblock %}

pg-codigo/codigo-symfony/templates/afastamento/index.html.twig
{% extends 'layouts/main.html.twig' %}

{% block title %}Afastamentos{% endblock %}

{% block body %}

    <div class="afastamento-index" style="padding-bottom: 20px;">

        <header class="content__title">
            <h1>Afastamentos</h1>
            <small>Acompanhe todos os afastamentos solicitados por professores</small>
        </header>

        <div class="card card-data-table">
            <div class="card-header" style="padding-bottom: 0;">
                <h2 class="card-title"></h2>
                <small class="card-subtitle"></small>

                <div class="collapse " id="filtros" aria-expanded="false" style="padding-bottom: 28px;">
                    <form action="" method="get" autocomplete="off">
                        <div class="row">
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label>Data da Solicitação</label>
                                    <input type="text" name="AfastamentoSearch[data_solicitacao]" class="form-control input-mask" data-mask="00/00/0000" autocomplete="off" maxlength="10">
                                    <i class="form-group__bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group form-group--float">
                                    <select class="form-control" name="AfastamentoSearch[professor_solicitante_id]" aria-invalid="false">
                                        <option value=""></option>
                                        {% for professor in professores %}
                                            <option value="{{ professor.id }}">{{ professor.nome }} {{ professor.sobrenome }}</option>
                                        {% endfor %}
                                    </select>
                                    <label class="form-control-label">Professor Solicitante</label>
                                    <i class="form-group__bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group form-group--float">
                                    <select class="form-control" name="AfastamentoSearch[tipo]" aria-invalid="false">
                                        <option value=""></option>
                                        <option value="nacional">Nacional</option>
                                        <option value="internacional">Internacional</option>
                                    </select>
                                    <label class="form-control-label">Tipo</label>
                                    <i class="form-group__bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group form-group--float">
                                    <select class="form-control" name="AfastamentoSearch[situacao]" aria-invalid="false">
                                        <option value=""></option>
                                        <option value="iniciado">Iniciado</option>
                                        <option value="aguardando_parecer_relator">Aguardando parecer relator</option>
                                        <option value="liberado">Liberado</option>
                                        <option value="aguardando_decisao_di">Aguardando decisão DI</option>
                                        <option value="aprovado_di">Aprovado DI</option>
                                        <option value="aprovado_ct">Aprovado CT</option>
                                        <option value="aprovado_prppg">Aprovado PRPPG</option>
                                        <option value="arquivado">Arquivado</option>
                                        <option value="cancelado">Cancelado</option>
                                        <option value="reprovado">Reprovado</option>
                                    </select>
                                    <label class="form-control-label">Situação</label>
                                    <i class="form-group__bar"></i>
                                </div>
                            </div>
                            <div class="col-lg-12" style="text-align: right">
                                <div class="btn-demo">
                                    <button type="submit" class="btn btn-outline-primary text-primary btn--icon-text waves-effect">Filtrar</button>				<button type="button" class="btn btn-link text-primary btn--icon-text waves-effect" style="padding-right: 0;" onclick="limparCampos(this)">Limpar filtros</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

                <script>
                    function limparCampos(botao){
                        $('#formsearch-nome').val('').removeClass('form-control--active');
                        $('#formsearch-email').val('').removeClass('form-control--active');
                        $('#formsearch-telefone').val('').removeClass('form-control--active');
                        $('#form-search').submit();
                    }
                </script>
                <div style="padding-right: 50px;">
                    <a class="btn btn-primary waves-effect" href="{{ path('afastamento_new') }}" style="margin-right: 10px; margin-bottom: 25px;">Quero solicitar meu afastamento</a>
                </div>
                <div class="actions">
                    <a class="actions__item collapsed" data-toggle="collapse" href="#filtros" aria-expanded="false" aria-controls="filtros"><i class="font-sendpayfont" style="font-size: 15px;">s</i></a>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr class="thead-default theme-options">
                            <th class="hidden-lg-down">Data da Solicitação</th>
                            <th class="hidden-lg-down">Professor Solicitante</th>
                            <th class="hidden-lg-down">Tipo</th>
                            <th class="hidden-lg-down">Situação</th>
                            <th class="hidden-lg-up">Afastamentos</th>
                            <th style="width: 134px; text-align: center;">Opções</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for afastamento in afastamentos %}
                        <tr>
                            <td class="hidden-lg-down">{{ afastamento.dataSolicitacao|date("d/m/Y") }}</td>
                            <td class="hidden-lg-down">{{ afastamento.professorSolicitante.nome }} {{ afastamento.professorSolicitante.sobrenome }}</td>
                            <td class="hidden-lg-down">{% if afastamento.tipo == 'internacional' %} <img src="{{ asset('images/mundo.svg') }}" alt="" style="width:30px;"> {% else %} <img src="{{ asset('images/brasil.svg') }}" alt="" style="width:30px;"> {% endif %}</td>
                            <td class="hidden-lg-down">
                                {% if afastamento.situacao == 'iniciado' %}
                                    <span class="badge badge-pill badge-primary">Iniciado</span>
                                {% elseif afastamento.situacao == 'aguardando_parecer_relator' %}
                                    <span class="badge badge-pill badge-warning">Aguardando parecer relator</span>
                                {% elseif afastamento.situacao == 'liberado' %}
                                    <span class="badge badge-pill badge-info">Liberado</span>
                                {% elseif afastamento.situacao == 'aguardando_decisao_di' %}
                                    <span class="badge badge-pill badge-warning">Aguardando decisão DI</span>
                                {% elseif afastamento.situacao == 'aprovado_di' %}
                                    <span class="badge badge-pill badge-success">Aprovado DI</span>
                                {% elseif afastamento.situacao == 'aprovado_ct' %}
                                    <span class="badge badge-pill badge-success">Aprovado CT</span>
                                {% elseif afastamento.situacao == 'aprovado_prppg' %}
                                    <span class="badge badge-pill badge-success">Aprovado PRPPG</span>
                                {% elseif afastamento.situacao == 'arquivado' %}
                                    <span class="badge badge-pill badge-default">Arquivado</span>
                                {% elseif afastamento.situacao == 'cancelado' %}
                                    <span class="badge badge-pill badge-default">Cancelado</span>
                                {% elseif afastamento.situacao == 'reprovado' %}
                                    <span class="badge badge-pill badge-danger">Reprovado</span>
                                {% else %}
                                    {{ afastamento.situacao }}
                                {% endif %}
                            </td>
                            <td class="hidden-lg-up">{{ afastamento.professorSolicitante.nome }}</td>
                            <td class="theme-options" style="width: 134px; justify-content: center; align-items: center !important; display: flex;">
                                <a href="{{ path('afastamento_show', {'id': afastamento.id}) }}" style="display: flex"><i class="font-sendpayfont text-primary">y</i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">Nenhum afastamento cadastrado</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

pg-codigo/codigo-symfony/templates/afastamento/new.html.twig
{% extends 'layouts/main.html.twig' %}

{% block title %}Solicitar meu afastamento{% endblock %}

{% block body %}

    <header class="content__title">
        <h1>Solicitar meu afastamento</h1>
    </header>

    {{ include('afastamento/_form.html.twig') }}

{% endblock %}